### ISSUE TITLE
Person Density Gradient - Big Idea

### ISSUE THREAD

**Issue by cadumas01** [D-S-Software/EpidemicSimulator#15]
- Allow for density of persons to be based on a two-variable function 
   -  SimBoard will be divided up into a very fine grid
        - Each point on the grid is a potential "hub"
   - A person checks if they should move to an area of higher density (in the direction of the partial x and y derivatives)
       - Take the person's current coordinates and plug into the density equation and run a check against these values
- Maybe allow for a few presets
- Make sure to allow for 2 variable function input for the user 
   - Ex: density, z = f ( x , y) = 4 - x^2 - y^2
![Screenshot 2020-10-13 180122](https://user-images.githubusercontent.com/39562430/95920840-2bfd6800-0d7e-11eb-85aa-dbb43663472d.png)

**Comment by 20lstrachan** [comment]
If this is still a possibility / fun to try we should make a new branch so we don't break things
