### ISSUE TITLE
Updated User Controls

### ISSUE THREAD

**Issue by cadumas01** [D-S-Software/EpidemicSimulator#2]
### Keybindings for action events
- Space to play/pause
- Enter to start simulation (already method called "start" in ControlPanel that the button action listener calls - that way you don't have to worry if user hits enter before parameters are filled as the method checks that)
- Arrow keys for speed
- S for settings
- I for info
- Any others for onscreen buttons?

**Comment by 20lstrachan** [comment]
Finished Implementing - See push comment for details
