### ISSUE TITLE
Code Clean Up - Very Important 

### ISSUE THREAD

**Issue by cadumas01** [D-S-Software/EpidemicSimulator#5]
- Use a common method to format repetitive GUI elements 
     - Already begun with final fields for colors
     - Make a public Formatter class with static methods (like CSS for java swing elements)

- Update Javadoc for method and add helper comments throughout complex parts

**Comment by 20lstrachan** [comment]
Also make sure methods are used in the appropriate class that it makes sense (help to reduce all the getters and setters as well as giving objects to other objects) Trying to have classes and objects be more self-contained

**Comment by 20lstrachan** [comment]
Completed the Formatter class that helped eliminate major sections of repeated code. This was completed in the first push named "Major Formatting Update"
